version: "3.7"
services:
  app:
    build:
      args:
        user: student
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: biblioteka
    container_name: biblioteka-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www

  db:
    image: mysql:8.0
    container_name: biblioteka-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  nginx:
    image: nginx:alpine
    container_name: biblioteka-nginx
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www
      - ./nginx:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  npm:
    image: node:alpine
    container_name: npm
    volumes:
      - ./:/var/www
    ports:
      - 3000:3000
    working_dir: /var/www
    profiles: ["npm"]
    entrypoint: ["npm"]
